spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.modulith.events.kafka.KafkaEventExternalizerConfiguration

logging:
  level:
    com.livecomerce: DEBUG
    org.springframework.security: TRACE
