ALTER TABLE lives ALTER COLUMN status TYPE VARCHAR(12);
ALTER TABLE lives DROP CONSTRAINT IF EXISTS lives_status_check;
ALTER TABLE lives ADD CONSTRAINT lives_status_check
    CHECK (status IN ('SCHEDULED', 'LIVE', 'RECONNECTING', 'ENDED', 'CANCELLED'));
